spring.application.name=practice-jpa-and-hibernate

spring.h2.console.enabled=true

# Browser url is localhost:8080/h2-console

# Create static URL for database
spring.datasource.url=jdbc:h2:mem:testdb

# This command prints SQL queries run by JPA, in terminal log.
spring.jpa.show-sql=true
