logging.level.org.springframework=debug
spring.profiles.active=prod

currency-service.url=http://default.sahilkrishna.com
currency-service.username=defaultusername
currency-service.key=defaultkey

#// To expose all the endpoints of actuator write this:
#management.endpoints.web.exposure.include=* // calling all endpoints uses a lot of memory so include specific endpoints only

#// include specific endpoints only
management.endpoints.web.exposure.include=health,metrics